# Generated by Django 4.1.1 on 2022-10-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
