# Generated by Django 4.1.1 on 2022-10-06 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_bid_time_remove_comment_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clothing/Footwear", "Clothing/Footwear"),
                    ("Books", "Books"),
                    ("Electronics", "Electronics"),
                    ("Cosmetics", "Cosmetics"),
                    ("Toys", "Toys"),
                    ("Home/Garden", "Home/Garden"),
                    ("Sport/Leisure", "Sport/Leisure"),
                ],
                max_length=32,
            ),
        ),
    ]
