# Generated by Django 4.1.1 on 2022-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_bid_time_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Bid time"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Comment time"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Time listed"),
        ),
    ]
