# Generated by Django 4.1.1 on 2022-10-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bid_time_alter_comment_time_alter_listing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
