# Generated by Django 4.1.1 on 2022-10-10 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_listing_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watcher",
        ),
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watching", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
