# Generated by Django 4.1.1 on 2022-10-12 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_comment_commenter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
